// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  pillars: dynamic(() => import("./Pillars")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  video: dynamic(() => import("./Video")),
};
